### PR TITLE
Drive: Add strict declare + better codeStyle.

### PR DESCRIPTION
**Pull request by janbarasek**
- Added `declare(strict_types=1);`
- Better CodeStyle by PhpStorm

For next commit I suggest use `\t` instead of spaces.

Thanks.

### CODE REVIEW

**Comment by basecardhero** [comment]
Hello. I apologize for the really long reply.

While I don't mind `declare(strict_types=1);`, this package follows [PSR-2](https://www.php-fig.org/psr/psr-2/) and the [PHP-FIG](https://www.php-fig.org/) standards, which is enforced by [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer). PSR-2 enforces the use of `spaces` over `tabs`.

**Comment by janbarasek** [comment]
Hello, ok I understand. I think you can keep current PSR and close this pull request. But I think strict declare policy is important.

What do you think? I can revert my changes and keep strict types only.

**Comment by basecardhero** [comment]
@janbarasek 

>What do you think? I can revert my changes and keep strict types only.

Please.

I will most likely bump this package to `1.0.0` since it _could_ possible break an existing application as this will cause Fatal Errors to be thrown ([source](https://www.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict)).

Thank you for doing this. I appreciate it.

**Comment by janbarasek** [comment]
I am not sure how implement it, because you want remove strict types. I think close this pull request will be better.

Thank you and have a lovely day. :)

**Pull request closed without merging**
